title: "So ... What I Do"
subtitle: "Reviews"
email: info@sowhatido.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/swid_coffee_logo.png'
favicon: 'assets/images/swid_coffee_favicon.ico'
author: Dex
paginate: 30
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-4638XVMXZJ

# Authors
authors:
  Dex:
    name: Dex
    display_name: Dex
    avatar: 'assets/images/dex.jpg'
    email: 'dex@sowhatido.com'
    description: ''

# Social
social:
  instagram: 
  facebook: 
  twitter:

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
